			$(document).on('click', '.back', function(){
				$('#newsLetter').show();
				$('#article').hide();
				
			});
			$(document).on('click', '.back1', function(){
				$('#teamBig').show();
				$('#member').hide();
				
			});
			
			$(document).on('click', '#news1', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/brazil.jpg"><p class="articleHeadLine">Brazilian Grand Prix - Making the best of a dry Friday<br><br></p><p class="articleText">10 Nov 2017<br>Seb and Kimi just under the 50-lap mark<br><br>Interlagos – Both practice sessions at the Autodromo Carlos Pace turned out to be quite uneventful, as despite the ever-present threat of rain, drivers only had to contend with a few intermittent and harmless drops during FP2. Scuderia Ferrari drivers jumped at the opportunity to rack up the laps of the 4.3 Km circuit, working mostly in preparation for Sunday’s race, which is supposed to be run in dry conditions. Sebastian covered 48 laps and Kimi 45.<br>“I think that in the end we ran more than what we expected as it didn’t rain”, Seb commented. “It was nice to be able to do a lot of laps today. We need to find the right balance and this should help us get the pace for the qualifying session and the race, but I still think it won’t be easy to defeat our main competitors. We’ll see where we get tomorrow”.<br>“It’s only a Friday”, said Kimi, “and as always, we keep trying different things to learn from them. The tires will play a key role here as usual, the performance will depend on how they work and how long they will last. I felt some vibrations at the beginning of my stint, but that’s quite normal to have sometimes in the car: usually it comes from tires and different sets. We don’t know what the temperatures will be over the rest of the weekend, but we cannot change them anyway and it will be the same for everybody”.<br>The third and final practice session will start tomorrow at 11 AM local time. There is a high chance of showers.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news2', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/brazil1.jpg"><p class="articleHeadLine">Brazilian Grand Prix - Free Practice gets underway at Interlagos</p><p class="articleText">10 Nov 2017<br>FP2 sees Seb finish fourth and Kimi sixth<br><br>Sao Paulo – In the second free practice session in Brazil, Sebastian Vettel was fourth fastest in 1’09”875, completing a total of 48 laps. Team-mate Kimi Raikkonen was sixth quickest with a 1’10”117, doing 45 laps.<br><br>Both Prancing Horse drivers ran the usual tyre programme, using new Softs and Supersofts, setting their best times of the afternoon on the latter. Tomorrow, the final hour of free practice at Interlagos gets underway at 14h00 CET, with qualifying following on at 17h00.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news3', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/brazil2.jpg"><p class="articleHeadLine">Brazilian Grand Prix - Free Practice gets underway at Interlagos</p><p class="articleText">10 Nov 2017<br>Kimi 3rd and Seb 6th in FP1<br><br>Sao Paulo – The penultimate round of the Formula 1 season, the Brazilian Grand Prix, has got underway with the usual first free practice session. The Ferraris are third and sixth on the time sheet, Kimi Raikkonen having posted a best lap of 1’09”744 and Sebastian Vettel doing a 1’09”984. Both Scuderia Ferrari men ran the same tyre programme, using the Medium and Supersoft compounds. The second session gets underway at 17h00 (CET.)</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news4', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/mexico1.jpg"><p class="articleHeadLine">Mexican Grand Prix - Kimi’s message to the fans<br><br></p><p class="articleText">30 Oct 2017<br>Right after the Mexican race, Kimi’s words for the fans<br><br>After yesterdays difficulties in qualifying, third place is not too bad, but obviously it is not what we were looking for. The start was not too bad, but then I moved to the left and lost the tow. I found myself blocked and lost many places in the first two corners. Then I had to wait for the cars in front to stop, to be able to push and gain positions. My car was a bit better than yesterday and we had decent speed. Once I was third, I could try to catch up, but I was too far from Valtteri and there was nothing I could really do. I focused on finishing the race and on keeping my position. This year we have made a good step forward from last season, but obviously we still have a few small things to improve. I think that in this season we have had a good and solid car. Lately we have had some issues, but the speed has been there. Obviously too many DNFs cost us a lot in the Championship. For next year we have to minimize those issues, improve things and learn from this season.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news5', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/mexico2.jpg"><p class="articleHeadLine">Mexican Grand Prix - Seb comments about the race</p><p class="articleText">29 Oct 2017<br><br>I know the team has been working hard, doing their best, but we didn’t achieve what we wanted to. It’s hard to cross the line realizing that you are not in the fight anymore. I fought to the end, giving everything I had. Then obviously in the last laps, when I had a big gap to Kimi, it would have been difficult for me to close it without something happening, like a Safety Car, but I was still believing. But in the end it didn’t happen. For sure it is not a great day for us, but it’s not about us today, it’s about Lewis and I congratulate him. Tomorrow you wake up and it will be a different day. The team is growing, and there are many positive aspects. Overall, I think we are on the right path.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news6', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/mexico3.jpg"><p class="articleHeadLine">Mexican Grand Prix - Kimi comments about the race</p><p class="articleText">29 Oct 2017<br><br>After yesterday’s difficulties in qualifying, third place is not too bad, but obviously it is not what we were looking for. The start was not too bad, but then I moved to the left and lost the tow. I found myself blocked and lost many places in the first two corners. Then I had to wait for the cars in front to stop, to be able to push and gain positions. My car was a bit better than yesterday and we had decent speed. Once I was third, I could try to catch up, but I was too far from Valtteri and there was nothing I could really do. I focused on finishing the race and on keeping my position. This year we have made a good step forward from last season, but obviously we still have a few small things to improve. I think that in this season we’ve had a good and solid car. Lately we’ve had some issues, but the speed has been there. Obviously too many DNFs cost us a lot in the Championship. For next year we have to minimize those issues, improve things and learn from this season.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#news7', function(){
				$('#newsLetter').hide();
				$('#article').show();
				$('#article').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika" align="left" src="img/maurizio.jpg"><p class="articleHeadLine">Mexican Grand Prix - Maurizio comments about the race</p><p class="articleText">29 Oct 2017<br><br>Once again today, the result of the race does not reflect the true potential of the SF70H. We saw that potential yesterday with pole position and again this afternoon, with several overtaking moves and the race fastest lap. Unfortunately, the collision at the first corner compromised the entire race. Right to the very end, the team fought for the chance of winning this world championship. We will now continue to do our very best in the two remaining Grands Prix, tackling them with the same level of concentration and determination. Congratulations to Lewis on his world championship title.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#drv1', function(){
				$('#teamBig').hide();
				$('#member').show();
				$('#member').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika1" align="left" src="img/sebp.jpg"><p class="profileHeadLine main">Sebastian Vettel</p><p class="profileHeadLine">AGE: 29<br>WEIGHT: 62kg<br>HEIGHT: 175cm<br>GRAND PRIX: 197<br>POLE POSITIONS: 50<br>RACE WINS: 47</p><p class="driverText">Sebastian Vettel was born on 3 July 1987 in Heppenheim, Germany. He began karting in 1991, aged three and in 1995 he started racing. Vettel won a series of karting titles, including the German Junior Karting Championship, the Monaco Kart Cup and the European Junior Karting Championship. In 2003, he graduated to single-seaters, taking part in the German Formula BMW series, in which he came second in his first season, winning the title the following year. In 2005, he finished fifth in the Formula 3 Euroseries and had his first taste of Formula 1, when he was given a test in a Williams. In 2006, he finished second in the Formula 3 Euroseries and became test driver for BMW Sauber. In 2007, Vettel began competing in the World Series by Renault and that same year he took over from Scott Speed in the Toro Rosso team, after the European Grand Prix. In 2008, he took his first win, at the Italian Grand Prix, the youngest ever Formula 1 winner.<br><br>He finished the season eighth and was rewarded with a move to Red Bull Racing. In 2009, he won in Shanghai, Silverstone and Suzuka, finishing second in the Drivers’ Championship. In 2010, Vettel became the youngest ever Formula 1 World Champion. He was totally dominant in 2011, winning 11 Grands Prix, taking his second world title, four races from the end of the season. In 2012 and 2013, he went on to secure his third and fourth titles, finishing fifth in 2014. In 2015 he finished third in his first season with Scuderia Ferrari and in 2016, he was fourth.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back1">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#drv2', function(){
				$('#teamBig').hide();
				$('#member').show();
				$('#member').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika1" align="left" src="img/kimip.jpg"><p class="profileHeadLine main">Kimi Räikkönen</p><p class="profileHeadLine">AGE: 37<br>WEIGHT: 62kg<br>HEIGHT: 175cm<br>GRAND PRIX: 270<br>POLE POSITIONS: 17<br>RACE WINS: 20</p><p class="driverText">Kimi-Matias Raikkonen was born in Espoo, Finland on 17 October 1979. He first tried karting at the age of three before going on to enjoy great success in this discipline, as from 1989. He won the Nordic Kart Championship at Varna, in Norway in 1998 and was second in the European Formula Super A Karting Championship in 1999. Switching to single-seaters, he then won the UK Formula Renault Championship in 2000. After taking part in several test with Sauber in Formula 1, Raikkonen signed for the Swiss team for the 2001 season, when he finished in the point four times.<br><br>In 2002, he joined McLaren, ending the year sixth, while the following year he came second, just two points behind Michael Schumacher. He spent three more years with the British team, before joining Ferrari in 2007 and winning the World Championship that same year.<br><br>He left the Scuderia at the end of 2009, spending 2010 and 2011 competing in the World Rally Championship and NASCAR. He then returned to Formula 1 with Lotus in 2012, where he spent two seasons. He rejoined the Scuderia in 2014, finishing eleventh in that year’s championship. In 2015 he was fourth and in 2016, he finished sixth.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back1">Back</button></div><div class="col-md-5"></div></div>');
			});
			$(document).on('click', '#drv3', function(){
				$('#teamBig').hide();
				$('#member').show();
				$('#member').html('<div class="row"><div class="col-md-1"></div><div class="col-md-10"><img class="slika1" align="left" src="img/antp.jpg"><p class="profileHeadLine main">Antonio Giovinazzi</p><p class="profileHeadLine">AGE: 23<br>WEIGHT: 70kg<br>HEIGHT: 183cm<br>GRAND PRIX: 2<br>POLE POSITIONS: 0<br>RACE WINS: 0</p><p class="driverText">Antonio Giovinazzi was born on 14th December 1993 in Martina Franca, in the Italian province of Taranto. He began karting in 2006 and won that year’s Italian National Trophy as well as the European championship in the 60cc category.<br><br>He made the move to single-seaters aged 19, racing in the Formula Pilota in China in 2012. The following year, he competed in the European Formula 3 championship driving for the Double R Racing team and also took part in the Formula 3 Masters. In 2014 he raced for the British Carlin team and the next year he competed in the Russian round of the DTM at the wheel of an Audi RS5 entered by Phoenix Racing.<br><br>He made his GP2 debut in 2016 with the Prema Powerteam, taking his first victory in the category at the Grand Prix of Europe and finished second overall in the championship with a total of five wins to his name. For 2017, he takes on the role of Scuderia Ferrari’s third driver.</p></div><div class="col-md-1"></div></div><div class="row"><div class="col-md-5"></div><div class="col-md-2"><button class="back1">Back</button></div><div class="col-md-5"></div></div>');
			});
